# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QDial, QDockWidget, QDoubleSpinBox, QFrame,
    QGridLayout, QGroupBox, QHeaderView, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QPlainTextEdit,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QTableView, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1850, 1009)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(250, 249, 248, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(204, 215, 196, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Widget.setPalette(palette)
        Widget.setCursor(QCursor(Qt.ArrowCursor))
        self.tabWidgetMain = QTabWidget(Widget)
        self.tabWidgetMain.setObjectName(u"tabWidgetMain")
        self.tabWidgetMain.setEnabled(True)
        self.tabWidgetMain.setGeometry(QRect(7, 61, 1171, 941))
        palette1 = QPalette()
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush1)
        brush3 = QBrush(QColor(229, 235, 225, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(102, 108, 98, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(136, 143, 130, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush8 = QBrush(QColor(0, 0, 0, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush9 = QBrush(QColor(102, 108, 98, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.tabWidgetMain.setPalette(palette1)
        self.tabWidgetMain.setAutoFillBackground(False)
        self.tabWidgetMain.setTabPosition(QTabWidget.North)
        self.tabWidgetMain.setTabShape(QTabWidget.Rounded)
        self.tab_stringModule = QWidget()
        self.tab_stringModule.setObjectName(u"tab_stringModule")
        self.groupBoxBasicTuningParameters = QGroupBox(self.tab_stringModule)
        self.groupBoxBasicTuningParameters.setObjectName(u"groupBoxBasicTuningParameters")
        self.groupBoxBasicTuningParameters.setGeometry(QRect(10, 60, 311, 141))
        self.comboBoxBaseNote = QComboBox(self.groupBoxBasicTuningParameters)
        self.comboBoxBaseNote.setObjectName(u"comboBoxBaseNote")
        self.comboBoxBaseNote.setGeometry(QRect(180, 60, 91, 25))
        self.label_7 = QLabel(self.groupBoxBasicTuningParameters)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 161, 21))
        self.label_8 = QLabel(self.groupBoxBasicTuningParameters)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 60, 161, 21))
        self.label_14 = QLabel(self.groupBoxBasicTuningParameters)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(280, 30, 21, 21))
        self.doubleSpinBoxFundamentalFrequency = QDoubleSpinBox(self.groupBoxBasicTuningParameters)
        self.doubleSpinBoxFundamentalFrequency.setObjectName(u"doubleSpinBoxFundamentalFrequency")
        self.doubleSpinBoxFundamentalFrequency.setGeometry(QRect(180, 30, 91, 26))
        self.doubleSpinBoxFundamentalFrequency.setAccelerated(True)
        self.doubleSpinBoxFundamentalFrequency.setDecimals(3)
        self.doubleSpinBoxFundamentalFrequency.setMaximum(1000.000000000000000)
        self.doubleSpinBoxFundamentalFrequency.setSingleStep(0.100000000000000)
        self.pushButton_12 = QPushButton(self.groupBoxBasicTuningParameters)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(10, 100, 261, 25))
        self.groupBoxBowParameters = QGroupBox(self.tab_stringModule)
        self.groupBoxBowParameters.setObjectName(u"groupBoxBowParameters")
        self.groupBoxBowParameters.setGeometry(QRect(10, 220, 1131, 201))
        self.label_13 = QLabel(self.groupBoxBowParameters)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 30, 161, 21))
        self.doubleSpinBoxBowMotorMaxSpeed = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowMotorMaxSpeed.setObjectName(u"doubleSpinBoxBowMotorMaxSpeed")
        self.doubleSpinBoxBowMotorMaxSpeed.setEnabled(False)
        self.doubleSpinBoxBowMotorMaxSpeed.setGeometry(QRect(170, 30, 91, 26))
        self.doubleSpinBoxBowMotorMaxSpeed.setMaximum(1000.000000000000000)
        self.label_17 = QLabel(self.groupBoxBowParameters)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(320, 30, 151, 21))
        self.doubleSpinBoxBowMotorMinSpeed = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowMotorMinSpeed.setObjectName(u"doubleSpinBoxBowMotorMinSpeed")
        self.doubleSpinBoxBowMotorMinSpeed.setEnabled(False)
        self.doubleSpinBoxBowMotorMinSpeed.setGeometry(QRect(480, 30, 91, 26))
        self.doubleSpinBoxBowMotorMinSpeed.setMaximum(150.000000000000000)
        self.doubleSpinBoxBowMaxPressure = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowMaxPressure.setObjectName(u"doubleSpinBoxBowMaxPressure")
        self.doubleSpinBoxBowMaxPressure.setGeometry(QRect(210, 80, 91, 26))
        self.doubleSpinBoxBowMaxPressure.setMaximum(65536.000000000000000)
        self.label_19 = QLabel(self.groupBoxBowParameters)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 80, 161, 21))
        self.label_20 = QLabel(self.groupBoxBowParameters)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(420, 80, 181, 21))
        self.doubleSpinBoxBowMinPressure = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowMinPressure.setObjectName(u"doubleSpinBoxBowMinPressure")
        self.doubleSpinBoxBowMinPressure.setGeometry(QRect(620, 80, 91, 26))
        self.doubleSpinBoxBowMinPressure.setMaximum(65536.000000000000000)
        self.label_21 = QLabel(self.groupBoxBowParameters)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(830, 80, 201, 21))
        self.doubleSpinBoxBowRestPosition = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowRestPosition.setObjectName(u"doubleSpinBoxBowRestPosition")
        self.doubleSpinBoxBowRestPosition.setGeometry(QRect(1030, 80, 91, 26))
        self.doubleSpinBoxBowRestPosition.setMaximum(65536.000000000000000)
        self.doubleSpinBoxBowMotorVoltage = QDoubleSpinBox(self.groupBoxBowParameters)
        self.doubleSpinBoxBowMotorVoltage.setObjectName(u"doubleSpinBoxBowMotorVoltage")
        self.doubleSpinBoxBowMotorVoltage.setEnabled(True)
        self.doubleSpinBoxBowMotorVoltage.setGeometry(QRect(770, 30, 91, 26))
        self.doubleSpinBoxBowMotorVoltage.setMaximum(10.000000000000000)
        self.doubleSpinBoxBowMotorVoltage.setSingleStep(0.100000000000000)
        self.label_18 = QLabel(self.groupBoxBowParameters)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(630, 30, 141, 21))
        self.comboBoxActuatorPreset = QComboBox(self.groupBoxBowParameters)
        self.comboBoxActuatorPreset.setObjectName(u"comboBoxActuatorPreset")
        self.comboBoxActuatorPreset.setGeometry(QRect(605, 160, 191, 25))
        self.comboBoxActuatorPreset.setEditable(True)
        self.label_3 = QLabel(self.groupBoxBowParameters)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(550, 160, 51, 17))
        self.pushButtonActuatorSave = QPushButton(self.groupBoxBowParameters)
        self.pushButtonActuatorSave.setObjectName(u"pushButtonActuatorSave")
        self.pushButtonActuatorSave.setGeometry(QRect(810, 160, 89, 25))
        self.pushButtonActuatorLoad = QPushButton(self.groupBoxBowParameters)
        self.pushButtonActuatorLoad.setObjectName(u"pushButtonActuatorLoad")
        self.pushButtonActuatorLoad.setGeometry(QRect(920, 160, 89, 25))
        self.pushButtonActuatorDelete = QPushButton(self.groupBoxBowParameters)
        self.pushButtonActuatorDelete.setObjectName(u"pushButtonActuatorDelete")
        self.pushButtonActuatorDelete.setGeometry(QRect(1030, 160, 89, 25))
        self.pushButton_9 = QPushButton(self.groupBoxBowParameters)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 110, 291, 25))
        self.pushButton_10 = QPushButton(self.groupBoxBowParameters)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(420, 110, 291, 25))
        self.pushButton_11 = QPushButton(self.groupBoxBowParameters)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(830, 110, 291, 25))
        self.line_3 = QFrame(self.groupBoxBowParameters)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 60, 1111, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.groupBoxBowParameters)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 140, 1111, 20))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.pushButton_13 = QPushButton(self.groupBoxBowParameters)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(1000, 30, 121, 25))
        self.pushButton_14 = QPushButton(self.groupBoxBowParameters)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(10, 160, 141, 25))
        self.label_22 = QLabel(self.tab_stringModule)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 10, 121, 21))
        self.comboBoxCurrentlySelectedModule = QComboBox(self.tab_stringModule)
        self.comboBoxCurrentlySelectedModule.setObjectName(u"comboBoxCurrentlySelectedModule")
        self.comboBoxCurrentlySelectedModule.setGeometry(QRect(130, 10, 321, 25))
        self.line = QFrame(self.tab_stringModule)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 40, 1141, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox_3 = QGroupBox(self.tab_stringModule)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 690, 1131, 211))
        self.tableViewScale = QTableView(self.groupBox_3)
        self.tableViewScale.setObjectName(u"tableViewScale")
        self.tableViewScale.setGeometry(QRect(10, 60, 1111, 111))
        self.tableViewScale.horizontalHeader().setDefaultSectionSize(90)
        self.pushButton = QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 180, 31, 21))
        self.pushButton_2 = QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(50, 180, 31, 21))
        self.pushButtonLoadHarmonicPreset = QPushButton(self.groupBox_3)
        self.pushButtonLoadHarmonicPreset.setObjectName(u"pushButtonLoadHarmonicPreset")
        self.pushButtonLoadHarmonicPreset.setGeometry(QRect(980, 180, 141, 25))
        self.comboBoxHarmonicPresets = QComboBox(self.groupBox_3)
        self.comboBoxHarmonicPresets.setObjectName(u"comboBoxHarmonicPresets")
        self.comboBoxHarmonicPresets.setGeometry(QRect(800, 180, 171, 25))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(740, 180, 51, 21))
        self.comboBoxHarmonicList = QComboBox(self.groupBox_3)
        self.comboBoxHarmonicList.setObjectName(u"comboBoxHarmonicList")
        self.comboBoxHarmonicList.setGeometry(QRect(110, 26, 141, 25))
        self.label_16 = QLabel(self.groupBox_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 30, 91, 17))
        self.pushButton_5 = QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(260, 30, 31, 21))
        self.pushButton_6 = QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(300, 30, 31, 21))
        self.groupBoxMuteParameters = QGroupBox(self.tab_stringModule)
        self.groupBoxMuteParameters.setObjectName(u"groupBoxMuteParameters")
        self.groupBoxMuteParameters.setGeometry(QRect(10, 530, 1131, 71))
        self.label_25 = QLabel(self.groupBoxMuteParameters)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 30, 91, 21))
        self.doubleSpinBoxMuteRestPosition = QDoubleSpinBox(self.groupBoxMuteParameters)
        self.doubleSpinBoxMuteRestPosition.setObjectName(u"doubleSpinBoxMuteRestPosition")
        self.doubleSpinBoxMuteRestPosition.setGeometry(QRect(110, 30, 65, 26))
        self.doubleSpinBoxMuteRestPosition.setMaximum(65536.000000000000000)
        self.label_26 = QLabel(self.groupBoxMuteParameters)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(200, 30, 121, 21))
        self.doubleSpinBoxMuteFullMutePosition = QDoubleSpinBox(self.groupBoxMuteParameters)
        self.doubleSpinBoxMuteFullMutePosition.setObjectName(u"doubleSpinBoxMuteFullMutePosition")
        self.doubleSpinBoxMuteFullMutePosition.setGeometry(QRect(330, 30, 65, 26))
        self.doubleSpinBoxMuteFullMutePosition.setMaximum(65536.000000000000000)
        self.doubleSpinBoxMuteHalfMutePosition = QDoubleSpinBox(self.groupBoxMuteParameters)
        self.doubleSpinBoxMuteHalfMutePosition.setObjectName(u"doubleSpinBoxMuteHalfMutePosition")
        self.doubleSpinBoxMuteHalfMutePosition.setGeometry(QRect(550, 30, 65, 26))
        self.doubleSpinBoxMuteHalfMutePosition.setMaximum(65536.000000000000000)
        self.label_27 = QLabel(self.groupBoxMuteParameters)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(420, 30, 131, 21))
        self.groupBoxSolenoidParameters = QGroupBox(self.tab_stringModule)
        self.groupBoxSolenoidParameters.setObjectName(u"groupBoxSolenoidParameters")
        self.groupBoxSolenoidParameters.setGeometry(QRect(10, 610, 1131, 71))
        self.label_32 = QLabel(self.groupBoxSolenoidParameters)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 111, 21))
        self.doubleSpinBoxSolenoidMinForce = QDoubleSpinBox(self.groupBoxSolenoidParameters)
        self.doubleSpinBoxSolenoidMinForce.setObjectName(u"doubleSpinBoxSolenoidMinForce")
        self.doubleSpinBoxSolenoidMinForce.setGeometry(QRect(120, 30, 65, 26))
        self.doubleSpinBoxSolenoidMinForce.setMaximum(65536.000000000000000)
        self.label_33 = QLabel(self.groupBoxSolenoidParameters)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(210, 30, 111, 21))
        self.doubleSpinBoxSolenoidMaxForce = QDoubleSpinBox(self.groupBoxSolenoidParameters)
        self.doubleSpinBoxSolenoidMaxForce.setObjectName(u"doubleSpinBoxSolenoidMaxForce")
        self.doubleSpinBoxSolenoidMaxForce.setGeometry(QRect(330, 30, 65, 26))
        self.doubleSpinBoxSolenoidMaxForce.setMaximum(65536.000000000000000)
        self.labelStringFrequency = QLabel(self.tab_stringModule)
        self.labelStringFrequency.setObjectName(u"labelStringFrequency")
        self.labelStringFrequency.setGeometry(QRect(700, 20, 111, 21))
        self.labelStringFrequency.setAlignment(Qt.AlignCenter)
        self.horizontalSliderStringFrequency = QSlider(self.tab_stringModule)
        self.horizontalSliderStringFrequency.setObjectName(u"horizontalSliderStringFrequency")
        self.horizontalSliderStringFrequency.setEnabled(True)
        self.horizontalSliderStringFrequency.setGeometry(QRect(700, 0, 160, 21))
        self.horizontalSliderStringFrequency.setMaximum(800)
        self.horizontalSliderStringFrequency.setValue(49)
        self.horizontalSliderStringFrequency.setTracking(True)
        self.horizontalSliderStringFrequency.setOrientation(Qt.Horizontal)
        self.horizontalSliderStringFrequency.setInvertedAppearance(False)
        self.horizontalSliderStringFrequency.setInvertedControls(False)
        self.horizontalSliderStringFrequency.setTickPosition(QSlider.TicksBelow)
        self.groupBox_2 = QGroupBox(self.tab_stringModule)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(340, 60, 321, 141))
        self.label_35 = QLabel(self.groupBox_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(230, 20, 61, 31))
        self.label_35.setAlignment(Qt.AlignCenter)
        self.labelAnalyzeNote = QLabel(self.groupBox_2)
        self.labelAnalyzeNote.setObjectName(u"labelAnalyzeNote")
        self.labelAnalyzeNote.setGeometry(QRect(0, 70, 81, 41))
        self.labelAnalyzeNote.setStyleSheet(u"font: 700 30pt \"Ubuntu\";")
        self.labelAnalyzeNote.setTextFormat(Qt.AutoText)
        self.labelAnalyzeNote.setAlignment(Qt.AlignCenter)
        self.labelAnalyzeFreq = QLabel(self.groupBox_2)
        self.labelAnalyzeFreq.setObjectName(u"labelAnalyzeFreq")
        self.labelAnalyzeFreq.setGeometry(QRect(240, 80, 41, 21))
        self.labelAnalyzeFreq.setAlignment(Qt.AlignCenter)
        self.labelAnalyzeCents = QLabel(self.groupBox_2)
        self.labelAnalyzeCents.setObjectName(u"labelAnalyzeCents")
        self.labelAnalyzeCents.setGeometry(QRect(120, 80, 41, 21))
        self.labelAnalyzeCents.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(110, 20, 61, 31))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.dialAnalyzeFreq = QDial(self.groupBox_2)
        self.dialAnalyzeFreq.setObjectName(u"dialAnalyzeFreq")
        self.dialAnalyzeFreq.setGeometry(QRect(200, 40, 121, 101))
        self.dialAnalyzeFreq.setMinimum(20)
        self.dialAnalyzeFreq.setMaximum(600)
        self.dialAnalyzeFreq.setNotchTarget(50.000000000000000)
        self.dialAnalyzeFreq.setNotchesVisible(True)
        self.dialAnalyzeCents = QDial(self.groupBox_2)
        self.dialAnalyzeCents.setObjectName(u"dialAnalyzeCents")
        self.dialAnalyzeCents.setGeometry(QRect(80, 40, 121, 101))
        self.dialAnalyzeCents.setMinimum(-50)
        self.dialAnalyzeCents.setMaximum(50)
        self.dialAnalyzeCents.setNotchTarget(10.000000000000000)
        self.dialAnalyzeCents.setNotchesVisible(True)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 20, 41, 31))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.dialAnalyzeFreq.raise_()
        self.dialAnalyzeCents.raise_()
        self.label_35.raise_()
        self.labelAnalyzeNote.raise_()
        self.labelAnalyzeFreq.raise_()
        self.labelAnalyzeCents.raise_()
        self.label_15.raise_()
        self.label_9.raise_()
        self.tabWidgetMain.addTab(self.tab_stringModule, "")
        self.tab_midiSettings = QWidget()
        self.tab_midiSettings.setObjectName(u"tab_midiSettings")
        self.comboBoxCurrentlySelectedModule_2 = QComboBox(self.tab_midiSettings)
        self.comboBoxCurrentlySelectedModule_2.setObjectName(u"comboBoxCurrentlySelectedModule_2")
        self.comboBoxCurrentlySelectedModule_2.setGeometry(QRect(110, 10, 321, 25))
        self.label_29 = QLabel(self.tab_midiSettings)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 10, 101, 21))
        self.pushButton_8 = QPushButton(self.tab_midiSettings)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(482, 10, 31, 25))
        self.pushButton_4 = QPushButton(self.tab_midiSettings)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(440, 10, 31, 25))
        self.groupBox = QGroupBox(self.tab_midiSettings)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 40, 1081, 601))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 171, 17))
        self.listWidgetMidiEvents = QListWidget(self.groupBox)
        self.listWidgetMidiEvents.setObjectName(u"listWidgetMidiEvents")
        self.listWidgetMidiEvents.setGeometry(QRect(12, 60, 191, 431))
        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(50, 500, 31, 25))
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 500, 31, 25))
        self.label_28 = QLabel(self.groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 540, 121, 17))
        self.lineEditMidiEventCommand = QLineEdit(self.groupBox)
        self.lineEditMidiEventCommand.setObjectName(u"lineEditMidiEventCommand")
        self.lineEditMidiEventCommand.setGeometry(QRect(10, 560, 1061, 25))
        self.listWidgetCommands = QListWidget(self.groupBox)
        self.listWidgetCommands.setObjectName(u"listWidgetCommands")
        self.listWidgetCommands.setGeometry(QRect(530, 61, 251, 281))
        self.listWidgetCommands.setDragEnabled(True)
        self.listWidgetCommands.setDragDropMode(QAbstractItemView.DragOnly)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(530, 40, 151, 17))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(230, 40, 171, 17))
        self.plainTextEditEventDescription = QPlainTextEdit(self.groupBox)
        self.plainTextEditEventDescription.setObjectName(u"plainTextEditEventDescription")
        self.plainTextEditEventDescription.setEnabled(False)
        self.plainTextEditEventDescription.setGeometry(QRect(230, 60, 241, 431))
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(483, 40, 31, 481))
        self.line_2.setFrameShadow(QFrame.Raised)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QFrame.VLine)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(810, 39, 251, 17))
        self.listWidgetModifiersVariables = QListWidget(self.groupBox)
        self.listWidgetModifiersVariables.setObjectName(u"listWidgetModifiersVariables")
        self.listWidgetModifiersVariables.setGeometry(QRect(810, 60, 251, 281))
        self.listWidgetModifiersVariables.setDragEnabled(True)
        self.listWidgetModifiersVariables.setDragDropMode(QAbstractItemView.DragOnly)
        self.plainTextEditCMVDescription = QPlainTextEdit(self.groupBox)
        self.plainTextEditCMVDescription.setObjectName(u"plainTextEditCMVDescription")
        self.plainTextEditCMVDescription.setEnabled(True)
        self.plainTextEditCMVDescription.setGeometry(QRect(530, 380, 531, 111))
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(530, 360, 171, 17))
        self.tabWidgetMain.addTab(self.tab_midiSettings, "")
        self.tab_cvmapping = QWidget()
        self.tab_cvmapping.setObjectName(u"tab_cvmapping")
        self.tab_cvmapping.setEnabled(True)
        self.groupBoxCV1 = QGroupBox(self.tab_cvmapping)
        self.groupBoxCV1.setObjectName(u"groupBoxCV1")
        self.groupBoxCV1.setGeometry(QRect(10, 10, 791, 181))
        self.dialCV1 = QDial(self.groupBoxCV1)
        self.dialCV1.setObjectName(u"dialCV1")
        self.dialCV1.setGeometry(QRect(4, 30, 71, 71))
        self.dialCV1.setMaximum(65535)
        self.dialCV1.setSingleStep(100)
        self.dialCV1.setPageStep(1000)
        self.dialCV1.setNotchesVisible(True)
        self.labelCV1 = QLabel(self.groupBoxCV1)
        self.labelCV1.setObjectName(u"labelCV1")
        self.labelCV1.setGeometry(QRect(10, 100, 61, 31))
        self.labelCV1.setAlignment(Qt.AlignCenter)
        self.labelCV2 = QLabel(self.groupBoxCV1)
        self.labelCV2.setObjectName(u"labelCV2")
        self.labelCV2.setGeometry(QRect(90, 100, 61, 31))
        self.labelCV2.setAlignment(Qt.AlignCenter)
        self.dialCV2 = QDial(self.groupBoxCV1)
        self.dialCV2.setObjectName(u"dialCV2")
        self.dialCV2.setGeometry(QRect(84, 30, 71, 71))
        self.dialCV2.setMaximum(65535)
        self.dialCV2.setSingleStep(100)
        self.dialCV2.setPageStep(1000)
        self.dialCV2.setNotchesVisible(True)
        self.dialCV3 = QDial(self.groupBoxCV1)
        self.dialCV3.setObjectName(u"dialCV3")
        self.dialCV3.setGeometry(QRect(164, 30, 71, 71))
        self.dialCV3.setMaximum(65535)
        self.dialCV3.setSingleStep(100)
        self.dialCV3.setPageStep(1000)
        self.dialCV3.setNotchesVisible(True)
        self.labelCV3 = QLabel(self.groupBoxCV1)
        self.labelCV3.setObjectName(u"labelCV3")
        self.labelCV3.setGeometry(QRect(170, 100, 61, 31))
        self.labelCV3.setAlignment(Qt.AlignCenter)
        self.dialCV4 = QDial(self.groupBoxCV1)
        self.dialCV4.setObjectName(u"dialCV4")
        self.dialCV4.setGeometry(QRect(244, 30, 71, 71))
        self.dialCV4.setMaximum(65535)
        self.dialCV4.setSingleStep(100)
        self.dialCV4.setPageStep(1000)
        self.dialCV4.setNotchesVisible(True)
        self.labelCV4 = QLabel(self.groupBoxCV1)
        self.labelCV4.setObjectName(u"labelCV4")
        self.labelCV4.setGeometry(QRect(250, 100, 61, 31))
        self.labelCV4.setAlignment(Qt.AlignCenter)
        self.labelCV7 = QLabel(self.groupBoxCV1)
        self.labelCV7.setObjectName(u"labelCV7")
        self.labelCV7.setGeometry(QRect(490, 100, 61, 31))
        self.labelCV7.setAlignment(Qt.AlignCenter)
        self.labelCV5 = QLabel(self.groupBoxCV1)
        self.labelCV5.setObjectName(u"labelCV5")
        self.labelCV5.setGeometry(QRect(330, 100, 61, 31))
        self.labelCV5.setAlignment(Qt.AlignCenter)
        self.dialCV7 = QDial(self.groupBoxCV1)
        self.dialCV7.setObjectName(u"dialCV7")
        self.dialCV7.setGeometry(QRect(484, 30, 71, 71))
        self.dialCV7.setMaximum(65535)
        self.dialCV7.setSingleStep(100)
        self.dialCV7.setPageStep(1000)
        self.dialCV7.setNotchesVisible(True)
        self.labelCV8 = QLabel(self.groupBoxCV1)
        self.labelCV8.setObjectName(u"labelCV8")
        self.labelCV8.setGeometry(QRect(570, 100, 61, 31))
        self.labelCV8.setAlignment(Qt.AlignCenter)
        self.dialCV6 = QDial(self.groupBoxCV1)
        self.dialCV6.setObjectName(u"dialCV6")
        self.dialCV6.setGeometry(QRect(404, 30, 71, 71))
        self.dialCV6.setMaximum(65535)
        self.dialCV6.setSingleStep(100)
        self.dialCV6.setPageStep(1000)
        self.dialCV6.setNotchesVisible(True)
        self.dialCV5 = QDial(self.groupBoxCV1)
        self.dialCV5.setObjectName(u"dialCV5")
        self.dialCV5.setGeometry(QRect(324, 30, 71, 71))
        self.dialCV5.setMaximum(65535)
        self.dialCV5.setSingleStep(100)
        self.dialCV5.setPageStep(1000)
        self.dialCV5.setNotchesVisible(True)
        self.dialCV8 = QDial(self.groupBoxCV1)
        self.dialCV8.setObjectName(u"dialCV8")
        self.dialCV8.setGeometry(QRect(564, 30, 71, 71))
        self.dialCV8.setMaximum(65535)
        self.dialCV8.setSingleStep(100)
        self.dialCV8.setPageStep(1000)
        self.dialCV8.setNotchesVisible(True)
        self.labelCV6 = QLabel(self.groupBoxCV1)
        self.labelCV6.setObjectName(u"labelCV6")
        self.labelCV6.setGeometry(QRect(410, 100, 61, 31))
        self.labelCV6.setAlignment(Qt.AlignCenter)
        self.tabWidgetMain.addTab(self.tab_cvmapping, "")
        self.tab_debugging = QWidget()
        self.tab_debugging.setObjectName(u"tab_debugging")
        self.gridLayoutWidget = QWidget(self.tab_debugging)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 40, 1151, 861))
        self.gridLayoutChart = QGridLayout(self.gridLayoutWidget)
        self.gridLayoutChart.setObjectName(u"gridLayoutChart")
        self.gridLayoutChart.setContentsMargins(0, 0, 0, 0)
        self.label_34 = QLabel(self.tab_debugging)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 10, 101, 21))
        self.label_34.setAlignment(Qt.AlignCenter)
        self.labelSetFrequency = QLabel(self.tab_debugging)
        self.labelSetFrequency.setObjectName(u"labelSetFrequency")
        self.labelSetFrequency.setGeometry(QRect(120, 10, 71, 21))
        self.labelSetFrequency.setAlignment(Qt.AlignCenter)
        self.horizontalSliderBowFrequency = QSlider(self.tab_debugging)
        self.horizontalSliderBowFrequency.setObjectName(u"horizontalSliderBowFrequency")
        self.horizontalSliderBowFrequency.setEnabled(True)
        self.horizontalSliderBowFrequency.setGeometry(QRect(200, 40, 160, 21))
        self.horizontalSliderBowFrequency.setMaximum(1000)
        self.horizontalSliderBowFrequency.setValue(0)
        self.horizontalSliderBowFrequency.setTracking(True)
        self.horizontalSliderBowFrequency.setOrientation(Qt.Horizontal)
        self.horizontalSliderBowFrequency.setTickPosition(QSlider.TicksBelow)
        self.labelBowFrequency = QLabel(self.tab_debugging)
        self.labelBowFrequency.setObjectName(u"labelBowFrequency")
        self.labelBowFrequency.setGeometry(QRect(330, 10, 111, 21))
        self.labelBowFrequency.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.tab_debugging)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(210, 10, 121, 21))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(self.tab_debugging)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(190, 10, 21, 21))
        self.line_8.setFrameShadow(QFrame.Plain)
        self.line_8.setFrameShape(QFrame.VLine)
        self.label_30 = QLabel(self.tab_debugging)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(460, 10, 131, 21))
        self.label_30.setAlignment(Qt.AlignCenter)
        self.horizontalSliderBowCurrent = QSlider(self.tab_debugging)
        self.horizontalSliderBowCurrent.setObjectName(u"horizontalSliderBowCurrent")
        self.horizontalSliderBowCurrent.setEnabled(True)
        self.horizontalSliderBowCurrent.setGeometry(QRect(510, 40, 160, 21))
        self.horizontalSliderBowCurrent.setMaximum(50)
        self.horizontalSliderBowCurrent.setPageStep(1)
        self.horizontalSliderBowCurrent.setValue(0)
        self.horizontalSliderBowCurrent.setTracking(True)
        self.horizontalSliderBowCurrent.setOrientation(Qt.Horizontal)
        self.horizontalSliderBowCurrent.setTickPosition(QSlider.TicksBelow)
        self.labelBowCurrent = QLabel(self.tab_debugging)
        self.labelBowCurrent.setObjectName(u"labelBowCurrent")
        self.labelBowCurrent.setGeometry(QRect(600, 10, 51, 21))
        self.labelBowCurrent.setAlignment(Qt.AlignCenter)
        self.line_9 = QFrame(self.tab_debugging)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(440, 10, 21, 21))
        self.line_9.setFrameShadow(QFrame.Plain)
        self.line_9.setFrameShape(QFrame.VLine)
        self.tabWidgetMain.addTab(self.tab_debugging, "")
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 14, 51, 17))
        self.comboBoxSerialPorts = QComboBox(Widget)
        self.comboBoxSerialPorts.setObjectName(u"comboBoxSerialPorts")
        self.comboBoxSerialPorts.setGeometry(QRect(70, 10, 691, 25))
        self.pushButtonConnectDisconnect = QPushButton(Widget)
        self.pushButtonConnectDisconnect.setObjectName(u"pushButtonConnectDisconnect")
        self.pushButtonConnectDisconnect.setGeometry(QRect(770, 10, 89, 25))
        self.pushButtonLoadFromModule = QPushButton(Widget)
        self.pushButtonLoadFromModule.setObjectName(u"pushButtonLoadFromModule")
        self.pushButtonLoadFromModule.setGeometry(QRect(1140, 10, 141, 25))
        self.pushButtonSaveToModule = QPushButton(Widget)
        self.pushButtonSaveToModule.setObjectName(u"pushButtonSaveToModule")
        self.pushButtonSaveToModule.setGeometry(QRect(990, 10, 141, 25))
        self.dockWidget = QDockWidget(Widget)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setGeometry(QRect(1189, 69, 661, 981))
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.plainTextEditSerialOutput = QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEditSerialOutput.setObjectName(u"plainTextEditSerialOutput")
        self.plainTextEditSerialOutput.setGeometry(QRect(0, 0, 651, 731))
        self.plainTextEditSerialOutput.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.plainTextEditSerialOutput.setReadOnly(False)
        self.pushButtonClear = QPushButton(self.dockWidgetContents)
        self.pushButtonClear.setObjectName(u"pushButtonClear")
        self.pushButtonClear.setGeometry(QRect(560, 740, 89, 25))
        self.lineEditSend = QLineEdit(self.dockWidgetContents)
        self.lineEditSend.setObjectName(u"lineEditSend")
        self.lineEditSend.setGeometry(QRect(0, 890, 461, 25))
        self.label_24 = QLabel(self.dockWidgetContents)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(230, 740, 61, 20))
        self.label_5 = QLabel(self.dockWidgetContents)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 870, 67, 17))
        self.spinBoxLimitLines = QSpinBox(self.dockWidgetContents)
        self.spinBoxLimitLines.setObjectName(u"spinBoxLimitLines")
        self.spinBoxLimitLines.setGeometry(QRect(154, 741, 71, 21))
        self.spinBoxLimitLines.setMaximum(10000)
        self.spinBoxLimitLines.setValue(2000)
        self.checkBoxLimitLines = QCheckBox(self.dockWidgetContents)
        self.checkBoxLimitLines.setObjectName(u"checkBoxLimitLines")
        self.checkBoxLimitLines.setGeometry(QRect(0, 740, 151, 21))
        self.checkBoxFilterCommAck = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterCommAck.setObjectName(u"checkBoxFilterCommAck")
        self.checkBoxFilterCommAck.setEnabled(False)
        self.checkBoxFilterCommAck.setGeometry(QRect(10, 790, 181, 23))
        self.label_4 = QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 770, 151, 17))
        self.checkBoxFilterUSB = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterUSB.setObjectName(u"checkBoxFilterUSB")
        self.checkBoxFilterUSB.setEnabled(False)
        self.checkBoxFilterUSB.setGeometry(QRect(10, 810, 171, 23))
        self.checkBoxFilterUSB.setCheckable(True)
        self.checkBoxFilterHardware = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterHardware.setObjectName(u"checkBoxFilterHardware")
        self.checkBoxFilterHardware.setEnabled(False)
        self.checkBoxFilterHardware.setGeometry(QRect(10, 830, 171, 23))
        self.checkBoxFilterError = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterError.setObjectName(u"checkBoxFilterError")
        self.checkBoxFilterError.setEnabled(False)
        self.checkBoxFilterError.setGeometry(QRect(250, 830, 171, 23))
        self.checkBoxFilterPriority = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterPriority.setObjectName(u"checkBoxFilterPriority")
        self.checkBoxFilterPriority.setEnabled(False)
        self.checkBoxFilterPriority.setGeometry(QRect(250, 810, 171, 23))
        self.checkBoxFilterUndefined = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterUndefined.setObjectName(u"checkBoxFilterUndefined")
        self.checkBoxFilterUndefined.setEnabled(False)
        self.checkBoxFilterUndefined.setGeometry(QRect(250, 790, 171, 23))
        self.checkBoxFilterDebug = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterDebug.setObjectName(u"checkBoxFilterDebug")
        self.checkBoxFilterDebug.setEnabled(False)
        self.checkBoxFilterDebug.setGeometry(QRect(480, 830, 171, 23))
        self.checkBoxFilterInfoRequest = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterInfoRequest.setObjectName(u"checkBoxFilterInfoRequest")
        self.checkBoxFilterInfoRequest.setEnabled(False)
        self.checkBoxFilterInfoRequest.setGeometry(QRect(480, 790, 171, 23))
        self.checkBoxFilterExpressionParser = QCheckBox(self.dockWidgetContents)
        self.checkBoxFilterExpressionParser.setObjectName(u"checkBoxFilterExpressionParser")
        self.checkBoxFilterExpressionParser.setEnabled(False)
        self.checkBoxFilterExpressionParser.setGeometry(QRect(480, 810, 171, 23))
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.checkBoxContinuousSMData = QCheckBox(Widget)
        self.checkBoxContinuousSMData.setObjectName(u"checkBoxContinuousSMData")
        self.checkBoxContinuousSMData.setGeometry(QRect(1300, 10, 151, 31))
        self.pushButtonReadSMData = QPushButton(Widget)
        self.pushButtonReadSMData.setObjectName(u"pushButtonReadSMData")
        self.pushButtonReadSMData.setGeometry(QRect(1460, 10, 151, 25))
        self.checkBox = QCheckBox(Widget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(1630, 10, 161, 23))
        self.checkBox_2 = QCheckBox(Widget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(870, 10, 101, 31))
        self.line_4 = QFrame(Widget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(970, 10, 21, 31))
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_5 = QFrame(Widget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(1280, 10, 21, 31))
        self.line_5.setFrameShadow(QFrame.Plain)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_6 = QFrame(Widget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(1610, 10, 21, 31))
        self.line_6.setFrameShadow(QFrame.Plain)
        self.line_6.setFrameShape(QFrame.VLine)

        self.retranslateUi(Widget)

        self.tabWidgetMain.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.groupBoxBasicTuningParameters.setTitle(QCoreApplication.translate("Widget", u"Basic tuning parameters", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Fundamental frequency", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Base note", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Hz", None))
        self.pushButton_12.setText(QCoreApplication.translate("Widget", u"Automatically find fundamental", None))
        self.groupBoxBowParameters.setTitle(QCoreApplication.translate("Widget", u"Basic bow parameters", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Motor max speed (Hz)", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Motor min speed (Hz)", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Bow max/stall pressure", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"Bow min contact pressure", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Bow rest/no contact position", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Bow motor voltage", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Preset", None))
        self.pushButtonActuatorSave.setText(QCoreApplication.translate("Widget", u"Save", None))
        self.pushButtonActuatorLoad.setText(QCoreApplication.translate("Widget", u"Load", None))
        self.pushButtonActuatorDelete.setText(QCoreApplication.translate("Widget", u"Delete", None))
        self.pushButton_9.setText(QCoreApplication.translate("Widget", u"Use current position as stall pressure", None))
        self.pushButton_10.setText(QCoreApplication.translate("Widget", u"Use current position as min. pressure", None))
        self.pushButton_11.setText(QCoreApplication.translate("Widget", u"Use current position as rest position", None))
        self.pushButton_13.setText(QCoreApplication.translate("Widget", u"Calibrate speed", None))
        self.pushButton_14.setText(QCoreApplication.translate("Widget", u"Calibrate pressure", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"Selected Module", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Widget", u"Harmonic series", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"+", None))
        self.pushButton_2.setText(QCoreApplication.translate("Widget", u"-", None))
        self.pushButtonLoadHarmonicPreset.setText(QCoreApplication.translate("Widget", u"Load preset", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"Preset", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Harmonic list", None))
        self.pushButton_5.setText(QCoreApplication.translate("Widget", u"+", None))
        self.pushButton_6.setText(QCoreApplication.translate("Widget", u"-", None))
        self.groupBoxMuteParameters.setTitle(QCoreApplication.translate("Widget", u"Mute parameters", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"Rest position", None))
        self.label_26.setText(QCoreApplication.translate("Widget", u"Full mute position", None))
        self.label_27.setText(QCoreApplication.translate("Widget", u"Half mute position", None))
        self.groupBoxSolenoidParameters.setTitle(QCoreApplication.translate("Widget", u"Hammer parameters", None))
        self.label_32.setText(QCoreApplication.translate("Widget", u"Minimum force", None))
        self.label_33.setText(QCoreApplication.translate("Widget", u"Maximum force", None))
        self.labelStringFrequency.setText(QCoreApplication.translate("Widget", u"110Hz / A2 - 0", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Widget", u"Pickup analysis", None))
        self.label_35.setText(QCoreApplication.translate("Widget", u"Freq", None))
        self.labelAnalyzeNote.setText(QCoreApplication.translate("Widget", u"A2", None))
        self.labelAnalyzeFreq.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelAnalyzeCents.setText(QCoreApplication.translate("Widget", u"0", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Cents", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Note", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_stringModule), QCoreApplication.translate("Widget", u"Module settings", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"Configuration", None))
        self.pushButton_8.setText(QCoreApplication.translate("Widget", u"-", None))
        self.pushButton_4.setText(QCoreApplication.translate("Widget", u"+", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"Configuration parameters", None))
        self.label.setText(QCoreApplication.translate("Widget", u"MIDI Events", None))
        self.pushButton_7.setText(QCoreApplication.translate("Widget", u"-", None))
        self.pushButton_3.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"Event commands", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"FAR Commands", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Event Description", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Modifiers and variables", None))
        self.label_31.setText(QCoreApplication.translate("Widget", u"Description", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_midiSettings), QCoreApplication.translate("Widget", u"MIDI settings", None))
        self.groupBoxCV1.setTitle(QCoreApplication.translate("Widget", u"CV #1", None))
        self.labelCV1.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV2.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV3.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV4.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV7.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV5.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV8.setText(QCoreApplication.translate("Widget", u"0", None))
        self.labelCV6.setText(QCoreApplication.translate("Widget", u"0", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_cvmapping), QCoreApplication.translate("Widget", u"CV Mapping", None))
        self.label_34.setText(QCoreApplication.translate("Widget", u"Set frequency", None))
        self.labelSetFrequency.setText(QCoreApplication.translate("Widget", u"???.?? Hz", None))
        self.labelBowFrequency.setText(QCoreApplication.translate("Widget", u"110Hz / A2 - 0", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"Motor frequency", None))
        self.label_30.setText(QCoreApplication.translate("Widget", u"Bow motor current", None))
        self.labelBowCurrent.setText(QCoreApplication.translate("Widget", u"1A", None))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_debugging), QCoreApplication.translate("Widget", u"Debugging", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Device", None))
        self.pushButtonConnectDisconnect.setText(QCoreApplication.translate("Widget", u"Connect", None))
        self.pushButtonLoadFromModule.setText(QCoreApplication.translate("Widget", u"Refresh", None))
        self.pushButtonSaveToModule.setText(QCoreApplication.translate("Widget", u"Save to module", None))
        self.plainTextEditSerialOutput.setPlaceholderText("")
        self.pushButtonClear.setText(QCoreApplication.translate("Widget", u"Clear", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"Lines", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Send", None))
        self.checkBoxLimitLines.setText(QCoreApplication.translate("Widget", u"Keep maximum of", None))
        self.checkBoxFilterCommAck.setText(QCoreApplication.translate("Widget", u"Command aknowledge", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Filter messages", None))
        self.checkBoxFilterUSB.setText(QCoreApplication.translate("Widget", u"USB Commands", None))
        self.checkBoxFilterHardware.setText(QCoreApplication.translate("Widget", u"Hardware messages", None))
        self.checkBoxFilterError.setText(QCoreApplication.translate("Widget", u"Error messages", None))
        self.checkBoxFilterPriority.setText(QCoreApplication.translate("Widget", u"Priority messages", None))
        self.checkBoxFilterUndefined.setText(QCoreApplication.translate("Widget", u"Undefined messages", None))
        self.checkBoxFilterDebug.setText(QCoreApplication.translate("Widget", u"Debug messages", None))
        self.checkBoxFilterInfoRequest.setText(QCoreApplication.translate("Widget", u"Info Requests", None))
        self.checkBoxFilterExpressionParser.setText(QCoreApplication.translate("Widget", u"Expression parser", None))
        self.checkBoxContinuousSMData.setText(QCoreApplication.translate("Widget", u"Continous readings", None))
        self.pushButtonReadSMData.setText(QCoreApplication.translate("Widget", u"Refresh data", None))
        self.checkBox.setText(QCoreApplication.translate("Widget", u"Send data after edit", None))
        self.checkBox_2.setText(QCoreApplication.translate("Widget", u"Persistance", None))
    # retranslateUi

